// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: order_items.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createOrderItem = `-- name: CreateOrderItem :one
INSERT INTO order_items (
    order_id, product_id, quantity, price
    )
VALUES (
    $1, $2, $3, $4
    )
RETURNING id, order_id, product_id, quantity, price, status, created_at, updated_at
`

type CreateOrderItemParams struct {
	OrderID   int32  `json:"order_id"`
	ProductID int32  `json:"product_id"`
	Quantity  int32  `json:"quantity"`
	Price     string `json:"price"`
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRowContext(ctx, createOrderItem,
		arg.OrderID,
		arg.ProductID,
		arg.Quantity,
		arg.Price,
	)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ProductID,
		&i.Quantity,
		&i.Price,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteOrderItem = `-- name: DeleteOrderItem :exec
DELETE FROM order_items
WHERE id = $1
`

func (q *Queries) DeleteOrderItem(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteOrderItem, id)
	return err
}

const getOrderItemsByOrderID = `-- name: GetOrderItemsByOrderID :many
SELECT id, order_id, product_id, quantity, price, status
FROM order_items
WHERE order_id = $1
ORDER BY id
`

type GetOrderItemsByOrderIDRow struct {
	ID        int32  `json:"id"`
	OrderID   int32  `json:"order_id"`
	ProductID int32  `json:"product_id"`
	Quantity  int32  `json:"quantity"`
	Price     string `json:"price"`
	Status    string `json:"status"`
}

func (q *Queries) GetOrderItemsByOrderID(ctx context.Context, orderID int32) ([]GetOrderItemsByOrderIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getOrderItemsByOrderID, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetOrderItemsByOrderIDRow{}
	for rows.Next() {
		var i GetOrderItemsByOrderIDRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.ProductID,
			&i.Quantity,
			&i.Price,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrderItemsByUser = `-- name: ListOrderItemsByUser :many
SELECT 
    oi.id AS order_item_id,
    oi.order_id,
    oi.product_id,
    oi.quantity,
    oi.price,
    oi.created_at AS item_created_at,
    oi.updated_at AS item_updated_at,

    o.status,
    o.total_amount,
    o.created_at AS order_created_at,
    o.updated_at AS order_updated_at
FROM order_items oi
INNER JOIN orders o ON oi.order_id = o.id
WHERE o.user_id = $1
ORDER BY oi.id
LIMIT $2 OFFSET $3
`

type ListOrderItemsByUserParams struct {
	UserID int32 `json:"user_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListOrderItemsByUserRow struct {
	OrderItemID    int32        `json:"order_item_id"`
	OrderID        int32        `json:"order_id"`
	ProductID      int32        `json:"product_id"`
	Quantity       int32        `json:"quantity"`
	Price          string       `json:"price"`
	ItemCreatedAt  time.Time    `json:"item_created_at"`
	ItemUpdatedAt  time.Time    `json:"item_updated_at"`
	Status         string       `json:"status"`
	TotalAmount    string       `json:"total_amount"`
	OrderCreatedAt sql.NullTime `json:"order_created_at"`
	OrderUpdatedAt time.Time    `json:"order_updated_at"`
}

func (q *Queries) ListOrderItemsByUser(ctx context.Context, arg ListOrderItemsByUserParams) ([]ListOrderItemsByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listOrderItemsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrderItemsByUserRow{}
	for rows.Next() {
		var i ListOrderItemsByUserRow
		if err := rows.Scan(
			&i.OrderItemID,
			&i.OrderID,
			&i.ProductID,
			&i.Quantity,
			&i.Price,
			&i.ItemCreatedAt,
			&i.ItemUpdatedAt,
			&i.Status,
			&i.TotalAmount,
			&i.OrderCreatedAt,
			&i.OrderUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrderItemStatus = `-- name: UpdateOrderItemStatus :exec
UPDATE order_items
SET status = $2
WHERE id = $1
`

type UpdateOrderItemStatusParams struct {
	ID     int32  `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateOrderItemStatus(ctx context.Context, arg UpdateOrderItemStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateOrderItemStatus, arg.ID, arg.Status)
	return err
}
